google-map-react/google-map-react

package.json
src/google_map.js

Add lodash polyfills for Number.isNaN & Number.isFinite

---

README.md

Pulled together from various sources (source code, closed issues etc.) Incomplete, but I hope it helps people getting started.

Add basic API docs and FAQs to the README

---

src/google_map.js

https://github.com/istarkov/google-map-react/pull/74

Api callback

---

package.json
src/google_map.js
src/utils/loaders/google_map_loader.js

This PR is related to this issue I was having: https://github.com/istarkov/google-map-react/issues/113
Turned out this issue was specific to my building process (some weird bug), but I think that'd be good to update lodash version to 4.x

update lodash version

---

src/google_map.js

Fix clientWidth of null

---

src/google_map_markers.js
test/components/GoogleMap.spec.js

It would be nice to have a class added to the marker to be able to animate its position. Even though animating top and left is not the most efficient method ever (transform is more performant) this is a good start (I can work on using transform to position the markers if you think it's a good idea).

Add class name to marker

---

src/google_map.js

closes #185

---

develop/GMap.js
develop/Main.js
develop/markers/SimpleMarker.js
src/google_map.js

Fix context

---

src/google_map_markers.js

Skip falsy markers

---

src/google_map.js

@istarkov Dynamic map options as per https://github.com/istarkov/google-map-react/pull/197
I was also using the develop section as a simple test playground - if you want to see/use the same you can see the (very simple) tests I was running with [here](https://github.com/alex-e-leon/google-map-react/commit/9ab1a5d7d9b4221e6feebb0e31d5bc8d453f15ca)

Allow gmap option props to be changed dynamically

---

README.md
develop/GMapLayers.js
develop/Layout.js
develop/Main.js
develop/data/fakeData.js
src/google_map.js

Hello, i have some issues for show google maps layers like a https://developers.google.com/maps/documentation/javascript/examples/layer-traffic or 
https://developers.google.com/maps/documentation/javascript/examples/layer-transit

#add layerTypes props handler, and GMapLayers view

---

src/google_map.js

Fixes a bug which prevented you from changing the function passed to the options prop

Fixed componentWillReceiveProps options function bug

---

README.md
src/google_map.js

This PR would expose the google maps event that says "hey, the user changed from satellite view to roads view" or vice versa. This is something I need to detect and change the icon styles based on so am looking to expose it. Any input is greatly appreciated!

expose map type callback

---

README.md
src/google_map.js
src/utils/geo.js
src/utils/utils.js

Hi, thanks for the great library it serving to me faithfully not first time. 
I found small problem with bounds object, most geo tools expect to receive data with NE and SW, instead of NW and SE. So i thought it will be cool if bounds object will contain all corners.

Add ne and sw to bounds object

---

src/google_map.js

Hey, my previous PR #291 is no longer needed. They fixed the bug in Inferno in the mean while! 
https://github.com/trueadm/inferno/issues/590#issuecomment-268852009
Here's a new PR to just fix that small add/remove typo.

fix small typo (add -> remove)

---

README.md

adding note about `resetBoundsOnResize` to readme

---

README.md

Add AnyReactComponent with jsbin example

---

develop/GMap.js
develop/GMapLayers.js
develop/GMapResizable.js
develop/markers/SimpleMarker.js
package.json
test/components/GoogleMap.spec.js
yarn.lock

- Added React as a peer dependency
- Upgraded dev dependencies to react 16.
- Moved PropTypes from 'react' to 'prop-types'

Added react 16 as peer dependency + bumped related react versions

---

API.md

https://stackoverflow.com/questions/8616764/what-is-the-sensor-parameter-in-google-places-api-good-for

Remove sensor parameter

---

.travis.yml

See https://github.com/istarkov/google-map-react/pull/483#issuecomment-353480981

Travis: Ensure that yarn.lock is up to date

---

src/google_map.js

Fixing marker position in Internet Explorer 11 in fullscreen mode.
Fixing: https://github.com/istarkov/google-map-react/issues/484

Add fullscreen check for Internet explorer 11

---

package.json

- Adds support for China https://github.com/istarkov/google-map-react/pull/494

Update version to 0.28.0

---

package.json

Fixes current release where region is required and it should be not.

Upgrade version to 0.29.0

---

package.json

Bump version to 0.32.0

---

API.md
README.md

Couple of improvements to our documentation:
- Updates example to use pure func components and prop-types.
- Move Heatmap example to `API.md`.
- Specify the necessity of a wrapper (Inspired by #542 thanks @iamkratos).

Improve documentation

---

CHANGELOG.md
DOC.md
README.md
bower.json
package.json

Move links to org instead of Ivan's repo, they were broken

---

develop/utils/props2Stream.js
src/google_map.js

Fix code styling in develop

---

src/google_heatmap.js

Added the possibility to add weights to the heatmap. 
There is already an open pr but they're not responding to the feedback. I need it for a project, hence my pr.
Passed linting :)

added feature to add weights to the heatmap

---

API.md

Better way to position a marker

Update 'positioning a marker' docs

---

package.json

Upgrade version to 1.0.5

---

src/utils/geo.js

Fix bug in fromContainerPixelToLatLng()

---

package.json

This version includes following changes:
- #620 Fix bug in fromContainerPixelToLatLng()
- #615 Add `onTilesLoaded` event listener

Bump version to 1.0.6

---

src/google_map.js

This allows the new context API to propagate context properly.
Fixes #642.

Use React 16 portal to render map overlay

---

package.json

Includes:
- #631 Add passive scroll
- #643 Use React 16 map portal to render map overlay

Bump version to 1.0.7

---

src/google_map.js

Reverts #643 which breaks for React versions prior to 16

Revert 643 fix/map context

---

API.md
src/google_map.js

Custom div style options

---

package.json

Version 1.0.9 includes 
- #634 Custom div style options

Bump version to 1.0.9

---

src/utils/utils.js

fixing issue 654 https://github.com/google-map-react/google-map-react/issues/654

add math abs to avoid negative values when calculating zoom

---

API.md
src/google_map.js

Goal:
Add possibility to work with google map api in the onDrag handler.
+ documentation improving

Pass map instance to onDrag handler

---

API.md
src/google_map.js
src/loaders/google_map_loader.js

When prop updateHeatmap is set to true --> map will rerender.
- New render of <GoogleMapReact> and data is changed, prop updateHeatmap should be true
- New render of <GoogleMapReact> and data is not changed, prop updateHeatmap should be false

Added feature: update heat map on data change + fix linting

---

API.md
src/google_map.js
src/loaders/google_map_loader.js

Reverts google-map-react/google-map-react#593
Due to change to the way we import libraries

Revert "Added feature: update heat map on data change + fix linting"

---

package.json

Bump to 1.1.1

---

API.md

This PR improves the documentation of the heatmap prop by adding types.
I don't mind adding PropTypes validation to this prop as well if you are interested in that.

Documentation: added PropTypes for heatmap prop

---

src/google_map.js

Each call to initialize a new map incurs an additional cost with Google's new billing platform.
In order to re-use the map instance between individual components, the following changes have been made:
1) Adds a `shouldUnregisterMapOnUnmount` prop to prevent the deletion of the map object, so it can be re-used.
2) Exposes the ref to the `googleMapDom_` via the `_onGoogleApiLoaded` callback, so it can be cached in a consuming application.

Add shouldUnregisterMapOnUnmount prop to persist map object on unmount

---

package.json
src/loaders/google_map_loader.js
yarn.lock

Reverts google-map-react/google-map-react#726

Revert "Google Map loader respecting the app language change"

---

src/google_map.js

Reverts google-map-react/google-map-react#722

Revert "Add shouldUnregisterMapOnUnmount prop to persist map object on unmount"

---

src/google_map.js

See previous discussion here #722 (comment)
Pls cut the tag just with this change; will help isolate bugs and prevent rolling back changes that didn't have defects
thanks!

Take #2: Add shouldUnregisterMapOnUnmount prop to persist map object on unmount

---

.npmignore

add dev folders into .npmignore, fixes #830

Add dev folders into .nmpignore

---

README.md

Include an example of clustering which loads/clusters remote data using hooks and modern React techniques.

Include updated example of clustering using hooks

---

LICENSE.md
README.md

Update License and Readme

---

src/google_map.js

Fix options not updated bug

---

package.json
src/index.cjs.js

Fixes https://github.com/google-map-react/google-map-react/issues/903
Related to https://github.com/google-map-react/google-map-react/pull/923
Source: https://github.com/developit/microbundle/issues/712

Produce CommonJS and UMD bundles

---

API.md
CHANGELOG.md
src/loaders/google_map_loader.js

Reverts #921 
Had many issues and was causing a breaking bug https://github.com/google-map-react/google-map-react/issues/931

Reverts PR #921 to fix #931

---

src/google_map.js

Change componentWillReceiveProps to componentDidUpdate

---

src/loaders/google_map_loader.js

Fix #954
Introduced in #942 and dragged to #946

Avoid multiple api loads

---

package.json
yarn.lock

Fixes https://github.com/google-map-react/google-map-react/issues/954

build(deps): update @googlemaps/js-api-loader

---

example/src/App.test.js
example/src/index.js
package.json
yarn.lock

React 18 in peer-dependencies and use new API
