google-map-react/google-map-react

- package.json
- src/utils/loaders/google_map_loader.js
Currently Internet Explorer 11 throws an error for 'Promise' not being defined. This PR utilizes this polyfill: https://github.com/jakearchibald/es6-promise to address the issue.
> Add and implement es6-promise for ie11 support

- README.md
addons has been separated to other packages
> Removed '/addons' in README example

- package.json
React 15.0 has been released in April, 2016.
Without this change, `npm@3` gives an `UNMET PEER DEPENDENCY` error and refuses to update the `npm-shrinkwrap.json`.
Additionally, update react devDependencies from `0.14.0-rc1` to `0.14.0`.
> Update react peerDependencies to 15.0.0

- src/google_map.js
I think there should be the check if old props center is set, otherwise latLng2Obj(this.props.center) fails.
> Added this.props.center check

- src/google_map.js
The current mouse/finger position is calculated on mousemove only right now. To support proper touch handling, a new position is now also calculated on click. This fixes #28.
There is another issue, if you move the finger around the map, for some reason the whole site moves too (iOS 9.3). So you can't navigate inside the map without scrolling the body. This is fixable with an onTouchMove (with `e.preventDefault()`) property on the parent div container of the map. I did not add it yet, because I'm not sure if this is a react issue or google did not prevent the events from bubbeling (what is weird because I can't reproduce this issue on a stand alone map without react).
> Calculate current touch position on click (fixes #28)

- README.md
`const {center, zoom} = fitBounds({nw, se}, size);`
{nw, se} are undefined
Need to pass bounds obect:
`const {center, zoom} = fitBounds(bounds, size);`
> Fix wrong decription of fitBounds() function. 

- src/google_map.js
Fixes https://github.com/istarkov/google-map-react/issues/232
Before: 
After:
> Fix ipad dragging issue

- README.md
More clearly show that `onClick` and `onChange` take objects as arguments.
> doc: clarify `onClick` and `onChange` arg structure

- src/google_map.js
When the resize event is triggered, the original center was lost. 
This issue is significant when the map is renders outside visible dom with zero height and width.
When placed into the visible dom, the resize is triggered correctly. With this change the center will persist. (Without this fix the old center is the top left corner)
> Keep original center on _mapDomResizeCallback

- src/google_map.js
Sorry, made a smal but ugly mistake in the last pull request.
The this.maps does not have a function getCenter .... but this.map does.
> Fix reference to maps instead of map

- API.md
- src/google_map.js
This should solve #297 and reverts the changes from #233.
The purpose of this PR is to expose the built in google maps functionality for handling touch interaction with the map and removing the previous handling which captured all touch events and emulated a "greedy" approach where the other elements on the page cannot respond to those touch events.
> Stop capturing all touch events and use built in google maps support

- src/google_map.js
This fixes #332 with a workaround for the detection of the presence of the mouse in the map.
See the original issue for reproduction and root cause.
> Fix unresponsive map after outside-click on a touch device with draggable:false

- package.json
- src/utils/geo.js
- src/utils/lib_geo/transform.js
Fixes: 
```
$ npm install
npm WARN deprecated point-geometry@0.0.0: This module has moved: please install @mapbox/point-geometry instead
```
> Move points-geometry dependency to organization

- src/google_map.js
On fullscreen mode, the view size should not be computed from the DOM element size, but from the `window` dimensions.
Fixes https://github.com/istarkov/google-map-react/issues/296
> Fix markers position on fullscreen mode

- src/google_map.js
When the google  fails to load due to no internet, the  call back should be notified so that appropriate UI can be shown
> notify call back of load failure

- API.md
- src/utils/loaders/google_map_loader.js
Use China specific API URL if setting bootstrapURLKeys.region to 'cn'.
Fixes #493
> Fix for usage from China

- src/utils/loaders/google_map_loader.js
Bah, sorry for stupid misstake. My PR (#494) to fix (#493) made the code break if not specifying bootstrapURLKeys.region. Sorry, here is a fix for that.
> Fix China fix making region required

- README.md
- develop/GMap.js
- develop/GMapHeatmap.js
- develop/GMapLayers.js
- develop/GMapOptim.js
- develop/GMapResizable.js
- develop/Layout.js
- develop/Main.js
- develop/data/fakeData.js
- src/google_heatmap.js
- src/google_map.js
- src/utils/loaders/google_map_loader.js
Hi, I have added heatmap functionality which is from default google map api.
**How it works**
Just need to pass prop of heatmap with GoogleMapReact component and all heatmap options are available like radius, opacity and gradient.
**Example**
```
<GoogleMapComp
lat={this.props.lat}
lng={this.props.lng}
zoom={this.props.zoom}
products={this.props.products}
heatmap={{
positions: [{
lat: 24.075,
lng: 54.947,
},
{
lat: 24.075,
lng: 54.940,
},
{
lat: 24.075,
lng: 54.943,
},
{
lat: 24.075,
lng: 54.933,
},
{
lat: 24.075,
lng: 54.923,
}],
options: {
radius: 20,
opacity: 0.7,
gradient: [
'rgba(0, 255, 255, 0)',
'rgba(0, 255, 255, 1)',
'rgba(0, 191, 255, 1)',
'rgba(0, 127, 255, 1)',
'rgba(0, 63, 255, 1)',
'rgba(0, 0, 255, 1)',
'rgba(0, 0, 223, 1)',
'rgba(0, 0, 191, 1)',
'rgba(0, 0, 159, 1)', …
```
> Added heatmap functionality

- .babelrc
- .gitignore
IE9 and IE10 require loose to work
your demo app doesn't work on IE9/10 so you will need to make a more simple one to test this fix out. the issue is to do with this.props not being avaiable in constructors for IE9/10 see: https://github.com/babel/babel/issues/3975 it was supposidly fixed 1 year ago but I can't see it working, maybe we need to swap to @babel/core to get this fix? I tried it but the change is made larger due to the curent demo apps build system.
Full fix would involve upgading to @babel/core + @babel/preset-env and migrating away from kotatsu in favour of a plain ole react app via webpack (create-react-app maybe?) and then place it into another folder and have that folder habing it's own package.json so we can consume google-map-react as if it were a real library during …
> Added loose to es2015 for IE10, IE11 support

- src/google_map.js
fix "Cannot read property 'fromLatLngToDivPixel' of undefined" #257
In my production, errors occurred in the `idle` event handler, not in the `draw()` function.
I can not find the condition, but I can reproduce this error in local env.
It looks like below.
> fix error about fromLatLngToDivPixel

- API.md
- src/google_map.js
Closes #505 
I removed the `minZoomOverride` option required for overriding the minZoom, I think its pretty clear that if we set a `minZoom`, we want to override it. 
@istarkov please let me know if you set the `minZoomOverride` for other important reason that I am missing, although I checked the code and it does not seem like it.
> Accept 0 as zoom value.

- src/utils/loaders/google_map_loader.js
Closes #510
Closes #526 
There are a couple of bugs involved in the latest release of Google Maps, both issues (#510 and #526) were caused by the version `3.32` which is **experimental**. [Quoting Google](https://developers.google.com/maps/documentation/javascript/versions):
> The experimental version — currently 3.32 — contains the latest features and bug fixes as they are made publicly available. Changes made to the experimental version are not guaranteed to be feature stable. We encourage you to regularly test your applications with the experimental version, which you can do by adding v=3.32 when loading the API
We would like our default version to be the latest **release** version, and not the latest **experimental** version. To do so we set up `v=3` if no version is specified by the …
> Set latest release version as default if user does not specify a version.

- .babelrc
- package.json
- yarn.lock
fix warning on installing packages (🙌 Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!)
> upgrade .babelrc

- develop/utils/props2Stream.js
- develop/utils/stream2Props.js
- develop/utils/withStateSelector.js
Introduced in #533 
I did not know that the method createHelper was private in recompose, but after a little bit of research. I found that it is actually not exposed. Source: https://github.com/acdlite/recompose/issues/66
Fixes error:
> Use private createHelper from recompose as its not exposed

- .flowconfig
- package.json
- src/google_map.js
- src/google_map_markers.js
- src/utils/shallowEqual.js
- yarn.lock
PR #440 Inspired me to use `shallowCompare` as much as possible to compare objects, mostly between `props` and `nextProps` or `prevProps`. 
Also, we were doing many checks by `!== undefined` or `=== undefined`, where we could just check with `isEmpty`, who also checks for the object being an empty string (`''`) or `null`. Which makes the code more solid.
> Use shallowEqual and isEmpty as much as possible

- develop/utils/omit.js
- develop/utils/props2Stream.js
- package.json
- yarn.lock
Refs: https://github.com/google-map-react/google-map-react/issues/558#issuecomment-380595616
Removes lodash completely as omit it is going away in lodash 5: https://github.com/lodash/lodash/issues/2930
> Use our own omit.js

- package.json
React-dom is required by [src/google_map.js](https://github.com/google-map-react/google-map-react/blob/master/src/google_map.js#L4). But it was not listed as peerDependency, because of this, we were not able to use Google-map-react in a project that does not have `react-dom` as a dependency.
> Move react-dom to dependencies

- src/google_map_markers.js
This lets you lock a component to a specific bounding rectangle, which allows for precise tiling during zoom with the experimental google maps API.
I work on a project that uses a technique similar to the thousands-of-markers sample project linked to from the readme.  If you run that project against the 3.32 google maps API you can see the same issue I was having.  The tiles are not scaled when frames are drawn during a zoom, which causes the edges to either have gaps between them, or to overlap.  This adds the option to specify a second LatLng (the southeast corner) to give a component a bounds-locked box to render into.
Here is a before example:
And after:
> Option to position and size components with two corners.

- src/google_map.js
Avoid the error "Cannot read property 'removeEventListener' of null"
> Avoid null error

- src/google_map.js
Fixes an issue where, even if the end user has a proper google maps API
mock, the GoogleMaps component will throw an error when in a test
env.  ReactDOM.findDOMNode(this.googleMapDom_) returns `null`.
This commit wraps the subsequent addEventListener call in an `if` block,
ensuring that an empty DOM doesn't add complications to test suites
Thank you for your consideration and your hard work on this great library!
> Add guard around mapDom event listener

- package.json
- yarn.lock
`react-dom` should be a `peerDep` and not a `dependancy`
Consumers should be deciding if they want to include this as part of their bundle not the library
> Move dep for react-dom

- API.md
People copy-paste a lot so we don't want them to get confused.
> Fix javascript typo

- API.md
- CHANGELOG.md
- package.json
- src/google_map.js
There are [some events](https://developers.google.com/maps/documentation/javascript/events) that are fired by the Google Maps JavaScript API, but there are not available on the React component. With this PR, I'm passing through the event `tilesloaded`.
Please let me know what you think about this. I'd love to see my changes upstream.
> Add prop `onTilesLoaded`

- src/google_map.js
- src/utils/detect.js
- src/utils/detectElementResize.js
- src/utils/passiveEvents.js
Added passive scroll event (which is more performant).
See: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener (`passive` in options)
Needed the feature detection for browsers that dont support it
**Note:** hard to test this as the demos for `google-map-react` are all busted due to incorrect google maps key
> Add passive scroll

- API.md
It is small fix in the example for Positioning a marker
> Small fix API.md

- package.json
- src/loaders/google_map_loader.js
- yarn.lock
**Problem**: When map language is dependent on app settings, the map doesn't respects current language and region value passed in `bootstrapURLKeys` object. New loader handles  `bootstrapURLKeys` change and reloads the Google Maps API (because of lack support to change language in API).
You can try this new loader here: [https://codesandbox.io/s/pppvk1o9z0](https://codesandbox.io/s/pppvk1o9z0)
> Google Map loader respecting the app language change

- develop/GMap.js
- develop/GMapHeatmap.js
- develop/GMapLayers.js
- develop/GMapOptim.js
- develop/GMapResizable.js
- develop/config/Google_API_key.js
- develop/data/fakeData.js
- develop/utils/withSafeInterval.js
- src/google_map.js
This PR is somewhere between a bug fix and a new feature.
Before this PR, if the heatmap positions prop was updated, the new data would not be displayed on the heatmap layer.
After this PR, if the heatmap.positions data is changed, then the heatmap layer will run a setData call and update the heatmap accordingly.
To demonstrate this, I updated the develop/GMapHeatmap.js example with a random data generator.
Along the way, I changed how the API key is set in the develop/ examples. I am happy to remove that change, but I think it's better this way. Additionally, I noticed that the API key in the develop folder doesn't work currently.
> Fix: Update heatmap layer when heatmap positions prop changes

- src/google_map.js
Pretty minor quibble, but it would be helpful to get the map's new zoom level returned on the zoom animation callbacks. 
Especially since they are already set up to pass params to the callback prop, but nothing is passed.
> Pass zoom value to zoom animation callbacks

- develop/utils/props2Stream.js
- develop/utils/stream2Props.js
- develop/utils/withStateSelector.js
- src/google_map.js
Projects using google-map-react as a dependency show console warnings about soon-to-be-deprecated lifecycle methods. React 17 will continue support for methods with the UNSAFE_ prefix, but not for unprefixed methods.
> Add UNSAFE_ prefix to deprecated lifecycle methods

- API.md
- CHANGELOG.md
- src/google_map.js
There is no callback dragEnd, which I feel would be a helpful callback to have.
The `dragEnd` event fired by the maps API fires as soon as the user releases the mouse, while the map inertia continues to pan the map. This callback therefore waits until the `idle` event is fired, then cleans up the event listener and invokes `props.dragEnd`
Please let me know if there's a better way to do this!
> Add prop 'onDragEnd'

- src/loaders/google_map_loader.js
Starting February 3, 2020, Google Maps Platform APIs will no longer be hosted from the google.cn domain. All requests to load Google Maps Platform APIs from the google.cn domain will return an error.
> Updated China base url

- src/google_map_markers.js
Resolves #843 
This should also negate the need to merge [this PR](https://github.com/google-map-react/google-map-react/pull/849)
The issue above was caused because the `pt` argument in `distanceToMouse` was undefined. Tracing backwards I found out that value corresponded to the `this.dimensionsCache_[childKey]` value in `GoogleMapMarkers`, which when an erroring, was an empty object.
Instead of inserting an empty object check into  `_onChangeHandler` in `GoogleMapMarkers` or overriding the `distanceToMouse` function on the child component, I went ahead and moved the `MarkerDispatcher` binds for `GoogleMapMarkers` into `componentDidMount`.
Previously, those binds were done in the constructor causing `dimensionsCache_` to be the default value (an empty object) instead of the updated value …
> Moves GoogleMapMarkers MarkerDispatcher binds to componentDidMount

- src/google_map.js
`this.props.options.minZoom` is not getting the value that's been passed (on window resize), instead getting `undefined` setting the minZoom level to default 3... should actually be `options.minZoom`
> On resize it's getting undefined minZoom

- README.md
I'm running Windows with WSL and came into this issue when trying to spin up the local dev environment.
After a little bit of searching i was able to solve it but I thought it would be a good a idea to add it to the readme in case anyone else hits the same issue.
> Added steps to manually link local module for development

- API.md
- src/google_map.js
- src/loaders/google_map_loader.js
Supports places, visualization, places, and geomerty libs.
keeps support for previous heatMapLibrary prop to avoid breaking older usage.
Closes #922
Closes #673
> Added all google maps api libraries to api loader

- API.md
- example/yarn.lock
- package.json
- src/loaders/google_map_loader.js
- yarn.lock
This PR is a cleaned and improved version of the following two PRS:
- #942 feat: use @googlemaps/js-api-loader
- #934 Fix libraries being repeated when using heatmapLibrary
Fixes #922, Resolves #708  
Both PRS had their errors and some unnecessary things, this PR fixes those errors and its a bit more cleaner.
Kindly asking for @aviyadeveloper and @jpoehnelt to review this code as they were the ones who had the initiative, I used some of @jpoehnelt commits and some ideas from @aviyadeveloper's PR #934 
BTW; I will be removing `heatmapLibrary` in the next major version.
> Use @googlemaps/js-api-loader and fix libraries usage

- src/loaders/google_map_loader.js
Fixes #947 
Key was not being set properly because [@google-maps/js-api-loader](https://github.com/googlemaps/js-api-loader) uses `apiKey` instead of `key` as a parameter.
Introduced in #942
> Fix key not being set in bootstrapURLKeys

- API.md
- CHANGELOG.md
- package.json
- src/google_map.js
- src/loaders/google_map_loader.js
- yarn.lock
- Remove `heatmapLibrary` that we flagged as deprecated in #948 
- Remove `apiKey` which has been deprecated for a long time
- Remove `onBoundsChange` which has been deprecated for a long time
> Remove deprecated props

- package.json
- src/loaders/google_map_loader.js
- yarn.lock
- Use single instance of Loader to avoid multiple api calls
- Update @googlemaps/js-api-loader to `1.7.0` that also takes care of this on their end
> Fix #954: Use single instance of Loader

- package.json
- yarn.lock
There are some nice changes since 1.7.0:
- googlemaps/js-api-loader#99 -- retries loading the Google Maps script
(which is a common source of error reports)
- googlemaps/js-api-loader#351 -- fixes bad promise rejection that was
reported by a user of google-maps-react
It's a fairly big version bump but the vast majority of changes are dev
dependency bumps.
> refactor: update @googlemaps/js-api-loader

- example/src/App.js
- example/src/App.test.js
- example/src/const/la_center.js
- example/src/index.js
- example/yarn.lock
- package.json
- src/google_map.js
- yarn.lock
Due to [React Strict Mode updates](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-strict-mode:~:text=To%20do%20this%2C%20React%20would%20unmount%20and%20remount%20trees%20using%20the%20same%20component%20state%20as%20before.) `markersDispatcher_` needs to be initialized on `componentDidMount`
This pull request fixes: 
- #1110 
- #1113 
- #1116 
- #1145
> Init markersDispatcher_ on componentDidMount

- src/google_map.js
Per https://github.com/google-map-react/google-map-react/issues/1238, `findDOMNode` is an artifact of some older code. We can use the `ref` directly.
> fix(src/google_map.js): remove unnecessary findDOMNode references

- src/google_map.js
- src/google_map_markers.js
Issue: (https://github.com/google-map-react/google-map-react/issues/1223)
This pull request addresses an issue with the markers rendering incorrectly using React `^18`. 
The issues were:
1. StrictMode behaves differently, which exposes an issue with the `dimensionsCache` property in `componentWillUnmount`.
https://react.dev/blog/2022/03/29/react-v18#new-strict-mode-behaviors
2. Batched updates, causing flickering with the markers when the map is repositioned or zoomed. Resolved by opting out of automatic batching for the marker state updates (via `flushSync`).
https://react.dev/blog/2022/03/29/react-v18#new-feature-automatic-batching
> Fix: React 18 markers
